# -*- coding: utf-8 -*-
"""Weather_AI_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZOakgGBzdBaPeYz7L9CcdOhE_nRpb9a
"""

from google.colab import userdata

GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")

!pip install -q langchain_google_genai langchain_community langchain_core requests duckduckgo-search

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
import requests

!pip install -U ddgs

#Now we will be preparing the tool required for our chatbot so basically the tool is online searching tool which can search on internet and fetch information

from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

result = search_tool.invoke("top news in India")
print(result)

# here we prepaered the llm for our chatbot



llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    temperature=0.7,
    google_api_key=GOOGLE_API_KEY
)

#testing if llm works fine

result = llm.invoke("hi")
print(result)

"""okay so till now we have a tool and a llm. Hence, we can create a model out of it"""

from langchain.agents import create_agent

agent = create_agent(
    model = llm,
    tools = [search_tool]
)

response = agent.invoke({
    "messages": [
        {"role": "user", "content": "3 ways to rech goa from delhi"}
    ]
})

print(response["messages"][-1].content)

"""okay so till now we build a very bsic ai agent now we ar going to improve it by adding one more tool to it

"""

from google.colab import userdata

OPENWEATHER_API_KEY = userdata.get("OPENWEATHER_API_KEY")

import requests
from langchain_core.tools import tool

@tool
def get_weather(city: str) -> str:
    """Get the current weather for a city."""

    url = "https://api.openweathermap.org/data/2.5/weather"

    params = {
        "q": city,
        "appid": OPENWEATHER_API_KEY,
        "units": "metric"
    }


    response = requests.get(url)

    return response.json()

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    temperature=0.7,
    google_api_key=GOOGLE_API_KEY
)

agent2 = create_agent(
    model = llm,
    tools = [search_tool, get_weather]
)

response = agent.invoke({
    "messages": [
        {"role": "user", "content": "which is the milleniuym city of India. Whats its current weather condition"}
    ]
})

print(response["messages"][-1].content)

"""This is a REACT agent

so clearly success now my ai agent can search on google about a place and based on the output can also tell the weather of that place

but as of now this method to make agents is outdated now its no more in use at industrial level for that there is the next library langraph
"""